/** Etiquetas en español — solicitud MUJERES 2000 (secciones 2.1–2.5, renovación, simulador). */

export const FL = {
  datos: {
    apellidoNombre: "Apellido y nombre",
    dni: "DNI",
    fechaNac: "Fecha de nacimiento",
    barrio: "Barrio",
    direccion: "Dirección",
    estadoCivil: "Estado civil",
    nivelEducativo: "Nivel educativo",
    telefono: "Teléfono",
    personasHogar: "Cantidad de personas en el hogar",
    personasIngresos: "Cantidad de personas que generan ingresos",
    planSocial: "¿Recibe plan social?",
    otroEmpleo: "¿Tiene otro empleo?",
    enBlanco: "¿Es en blanco?",
    monotributo: "¿Tiene monotributo?",
    banco: "Banco",
    cbuCvu: "CBU / CVU",
  },
  emprendimiento: {
    rubro: "Rubro (comercial / productivo / servicio)",
    descripcion: "Descripción del emprendimiento",
    funcionamiento: "¿Está en funcionamiento?",
    antiguedad: "Antigüedad",
    objetivo: "Objetivo del emprendimiento",
    usoGanancia: "Uso de la ganancia",
    estacionalidad: "Estacionalidad",
    proveedores: "Proveedores",
    clientes: "Clientes",
    modalidadCobro: "Modalidad de cobro",
    promocion: "Estrategia de promoción",
    competencia: "Competencia",
    diferenciacion: "Diferenciación",
  },
  produccion: {
    participan: "Personas que participan",
    tareas: "Distribución de tareas",
    horas: "Horas dedicadas semanalmente",
    bienes: "Bienes de capital",
  },
  redes: {
    instagram: "Instagram",
    facebook: "Facebook",
    otros: "Otros",
  },
  docs: {
    fotos: "Observaciones sobre las fotos (opcional)",
    presEmp: "Presupuesto del emprendimiento",
    presFam: "Presupuesto familiar",
    ventas: "Ventas",
  },
  renovacion: {
    title: "Datos del crédito anterior",
    saldo: "Saldo actual",
    montoUltimo: "Monto último préstamo",
    fechaInicio: "Fecha inicio",
    fechaCancel: "Fecha cancelación",
    cuotas: "Cantidad de cuotas",
    evalTitle: "Evaluación del desempeño",
    actividad: "Actividad",
    pagoCuotas: "Pago de cuotas",
    asistencia: "Asistencia",
    evolucion: "Evolución del emprendimiento",
    checklist: "Checklist",
    monotributo: "Monotributo",
    capitalizacion: "Capitalización",
    canales: "Incremento de canales de venta",
  },
  sim: {
    monto: "Monto deseado (USD)",
    cuotas: "Cantidad de cuotas",
    tna: "TNA % (anual nominal)",
  },
  opciones: {
    siNo: ["Sí", "No", "No aplica"],
    rubro: ["Comercial", "Productivo", "Servicio"],
    desempeno: ["Muy bueno", "Bueno", "Regular", "Malo"],
  },
} as const;
